# MICRON.LIV.SML.SP.MCR.AWS
# [micron-ceml-lcl-others]
# Windows Server 2012 R2 Version 6.2 (Build 9200)

---
ansible_host: 172.0.9.86
new_relic_log: log-disabled
location: us_east_nvirginia
region: us-east-1
bcdr: P2
product: "lawcruit_legacy / ce_manager_legacy"
env: Dev
owner: "Felix Pamittan / Janine Lim / Melvin Libunao"
creationdate: "2012-01-01"

...